{
 "title": "1.- Agent Process Metrics",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "log_category",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Antrea Managed Pods by Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_agent_local_pod_count{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_local_pod_count{instance=~\"^$instance.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Antrea Process",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"^$instance.*\"}[1m])  * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server CPU Usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\".*6443$\"} [1m]) * 100",
     "legendFormat": "min {{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Resident and Memory Status ",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\".*6443$\"}",
     "legendFormat": "resident memory @ {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\".*6443$\"}",
     "legendFormat": "virtual memory @ {{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Status",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory Status",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Antrea Logs per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (log_level) (rate({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m]))",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "description": "Open File Descriptors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(process_max_fds{instance=~\"^$instance.*\"})\n",
     "legendFormat": "Max FDs"
    }
   ]
  }
 ]
}
{
 "title": "2.- Agent OVS Metrics and logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   { "name": "ovs_table", "query": { "query": "antrea_agent_ovs_flow_count" } },
   {
    "name": "operation",
    "query": {
     "query": "antrea_agent_ovs_flow_ops_count"
    }
   },
   {
    "name": "ovs_log_level",
    "query": {}
   },
   {
    "name": "ovs_category",
    "query": {}
   },
   {
    "name": "ip_family",
    "query": {
     "query": "antrea_proxy_total_endpoints_installed"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVS Table Names",
   "type": "text",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "0=PipelineRootClassifier\n1=ARPSpoofGuard\n2=ARPResponder\n3=Classifier\n4=SpoofGuard\n5=UnSNAT\n7=ConntrackZone\n8=PreRoutingClassifier\n9=SessionAffinity\n10=ServiceLB\n11=EndpointDNAT\n12=AntreaPolicyEgressRule\n13=EgressRule\n14=EgressDefaultRule\n15=EgressMetric\n16=L3Forwarding\n17=EgressMark\n18=L3DecTTL\n19=SNATMark\n20=SNAT\n21=L2ForwardingCalc\n22=TrafficControl\n23=IngressSecurityClassifier\n24=AntreaPolicyIngressRule\n25=IngressRule\n26=IngressDefaultRule\n27=IngressMetric\n28=ConntrackCommit\n29=Output"
   }
  },
  {
   "title": "Agent OVS Flow Count",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}",
     "legendFormat": "table {{table_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "Sum of OVS Entries by Node",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum (antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}) by (instance)",
     "legendFormat": "entries @ {{instance}}"
    }
   ]
  },
  {
   "title": "Sum of OVS Entries by TableID",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum (antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}) by (table_id)",
     "legendFormat": "table {{table_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "OVS Flow Operations by instance",
   "type": "timeseries",
   "description": "Number of OVS flow operations, partitioned by operation type (add, modify and delete).",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(antrea_agent_ovs_flow_ops_count{instance=~\"^$instance.*\", operation=~\"$operation\"}[1m])) by (instance) * 60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  {
   "title": "OVS Flow Operations by operation type",
   "type": "timeseries",
   "description": "Number of OVS flow operations, partitioned by operation type (add, modify and delete).",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(antrea_agent_ovs_flow_ops_count{instance=~\"^$instance.*\", operation=~\"$operation\"}[1m])) by (operation) * 60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  {
   "title": "Flow Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(antrea_agent_ovs_flow_ops_error_count{instance=~\"$instance.*\"}[1m]) *60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  { "title": "OVS Logs Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "OpenvSwitch Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-ovs\",ovs_category=~\"$ovs_category\",ovs_log_level=~\"$ovs_log_level\", nodename=~\"$instance\"} |  json | line_format \"{{.date}} at node {{.nodename}} with level {{.ovs_log_level}} from subsystem {{.ovs_category}} with message: {{.message}}\""
    }
   ]
  },
  {
   "title": "OVS  Events per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"fluentbit-antrea-ovs\", nodename=~\"$instance\", ovs_category=~\"$ovs_category\", ovs_log_level=~\"$ovs_log_level\"} [1m])) by (ovs_log_level)",
     "legendFormat": "{{ovs_log_level}} {{ovs_category}} "
    }
   ]
  }
 ]
}
{
 "title": "3.-  Agent Conntrack and Proxy Metrics",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "ip_family",
    "query": {
     "query": "antrea_proxy_total_endpoints_installed"
    }
   }
  ]
 },
 "panels": [
  { "title": "Conntrack Section", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Antrea ZoneID Conntrack Connection Count",
   "type": "timeseries",
   "description": "antrea_agent_conntrack_total_connection_count: Number of connections in the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_antrea_connection_count: Number of connections in the Antrea ZoneID of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_max_connection_count: Size of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "antrea_agent_conntrack_antrea_connection_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CT Total Connection vs Maximum Percentage",
   "type": "timeseries",
   "description": "antrea_agent_conntrack_total_connection_count: Number of connections in the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_antrea_connection_count: Number of connections in the Antrea ZoneID of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_max_connection_count: Size of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(antrea_agent_conntrack_total_connection_count{instance=~\"^$instance.*\"}/antrea_agent_conntrack_max_connection_count{instance=~\"^$instance.*\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy and Endpoints Section", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Proxy Endpoints vs Service Updates rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(antrea_proxy_total_endpoints_updates{job=\"antrea-agents\", instance=~\"^$instance.*\"} [$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(antrea_proxy_total_services_updates{job=\"antrea-agents\", instance=~\"^$instance.*\"} [$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Endpoints Installed by Node",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_proxy_total_endpoints_installed {job=\"antrea-agents\", instance=~\"^$instance.*\", ip_family=~\"$ip_family\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "4.- Agent Network Policy Metrics and Logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "action",
    "query": {}
   },
   { "name": "sourceIP_filter", "label": "src_IP" },
   { "name": "destinationIP_filter", "label": "dest_IP" }
  ]
 },
 "panels": [
  {
   "title": "Network Policies by Node ",
   "type": "stat",
   "description": "Number of NetworkPolicies on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_agent_networkpolicy_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Egress Network Policies",
   "type": "stat",
   "description": "Number of egress NetworkPolicy rules on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_egress_networkpolicy_rule_count{instance=~\"^$instance.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Denied Connection Count by Node",
   "type": "timeseries",
   "description": "Number of denied connections detected by Flow Exporter deny connections tracking. This metric gets updated when a flow is rejected/dropped by network policy.",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "antrea_agent_denied_connection_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Ingress Network Policies",
   "type": "stat",
   "description": "Number of ingress NetworkPolicy rules on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_ingress_networkpolicy_rule_count{instance=~\"^$instance.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Hitting Network Policy by Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (action) (sum_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"$action\"} | json | unwrap packetLength | __error__=\"\" | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__interval]))\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Network Policy Hits by Action",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"$action\"} | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\"[$__range])) by (action)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Network Policies Log Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Antrea Network Policy Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-netpolicy\",action=~\"$action\", nodename=~\"$instance\"} \n|  json \n|  line_format \"🛡️ {{.action}} {{.protocol}} packet from Source:{{.sourceIP}}:{{.sourcePort}} to Destination:{{.destinationIP}}:{{.destinationPort}} hitting rule {{.ruleName}} with reference {{.antreaNativePolicyReference}} at node {{.nodename}}\" \n| sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\""
    }
   ]
  },
  { "title": "Allowed Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Top Allowed Rules Hits by Name",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ruleName) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range]))",
     "legendFormat": "{{ruleName}}"
    }
   ]
  },
  {
   "title": "Top Allowed DestinationIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(destinationIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Top Allowed SourceIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (sourceIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{sourceIP}}"
    }
   ]
  },
  {
   "title": "Allowed Services",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationPort, protocol, action) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])) ",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Top Allowed Conversations",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by(protocol, sourceIP, destinationIP, destinationPort) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\"[$__range])))",
     "legendFormat": "{{sourceIP}} - {{destinationIP}} {{protocol}} {{destinationPort}}"
    }
   ]
  },
  { "title": "Denied Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Top Denied Rules Hits by Name",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by(ruleName) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Reject|Drop\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{ruleName}}"
    }
   ]
  },
  {
   "title": "Top Denied SourceIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (sourceIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{sourceIP}}"
    }
   ]
  },
  {
   "title": "Top Denied DestinationIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (destinationIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Denied Services",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationPort, protocol, action) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Reject|Drop\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range]))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Top Denied Conversations",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2, sum by (protocol, sourceIP, destinationIP, destinationPort) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` | sourceIP =~\".*$sourceIP_filter\" and destinationIP =~\".*$destinationIP_filter\" [$__range])))",
     "legendFormat": "{{sourceIP}} - {{destinationIP}} {{protocol}} {{destinationPort}}"
    }
   ]
  }
 ]
}
{
 "title": "5.- Antrea Agent Logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   },
   {
    "name": "log_category",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Antrea Logs by Node",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (count_over_time({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs by log level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (log_level) (count_over_time({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs in Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Agent Logs count by Category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(agent_log_category) (count_over_time({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Antrea Log Count Time Series by Category and Log Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (agent_log_category, log_level) (count_over_time({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\" } | json  [$__range]))",
     "legendFormat": "{{log_level}} {{agent_log_category}} "
    }
   ]
  },
  {
   "title": "Antrea Rate Events per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m])) by (log_level)",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Antrea Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\" } | json | line_format `{{.timestamp}} at node {{.nodename}} with level {{.log_level}} from subsystem {{.agent_log_category}} with message: {{.message}}`"
    }
   ]
  }
 ]
}
{
 "title": "6.- Controller Metrics and Logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-controllers\"}"
    }
   },
   {
    "name": "log_category",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Logs by log level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (log_level) (count_over_time({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs count by Category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller_log_category) (count_over_time({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__range]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Antrea Controller Logs per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m])) by (log_level)",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Queue Lenght",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "antrea_controller_length_address_group_queue",
     "legendFormat": "Address Group Queue"
    },
    {
     "expr": "antrea_controller_length_network_policy_queue",
     "legendFormat": "Network Policy Queue"
    },
    {
     "expr": "antrea_controller_length_applied_to_group_queue",
     "legendFormat": "Applied To Queue"
    }
   ]
  },
  {
   "title": "Nodes Running Antrea Controller",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "up{job=\"antrea-controllers\", instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Process CPU Seconds",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"antrea-controllers\"}[60s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(antrea_controller_network_policy_sync_duration_milliseconds_sum[1m])",
     "legendFormat": "Network Policy Sync Duration (msec)"
    },
    {
     "expr": "irate(antrea_controller_address_group_sync_duration_milliseconds_sum[1m])",
     "legendFormat": "Address Group Sync Duration (msec)"
    },
    {
     "expr": "rate(antrea_controller_applied_to_group_sync_duration_milliseconds_sum[1m])",
     "legendFormat": "Applied-to-Group Sync Duration (msec)"
    }
   ]
  },
  {
   "title": "Controller Processed Rate",
   "type": "timeseries",
   "description": "antrea_controller_address_group_processed: The total number of address-group processed\n\nantrea_controller_applied_to_group_processed: The total number of applied-to-group processed\n\nantrea_controller_network_policy_processed: The total number of internal-networkpolicy processed",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "irate(antrea_controller_network_policy_processed[1m])",
     "legendFormat": "Network Policy Processed"
    },
    {
     "expr": "irate(antrea_controller_applied_to_group_processed[1m])",
     "legendFormat": "Applied-to-Group Processed"
    },
    {
     "expr": "irate(antrea_controller_address_group_processed[1m])",
     "legendFormat": "Address Groups Processed"
    }
   ]
  },
  {
   "title": "ANP and ACNP Status Update Rate",
   "type": "timeseries",
   "description": "antrea_controller_acnp_status_updates: The total number of actual status updates performed for Antrea ClusterNetworkPolicy Custom Resources\n\nantrea_controller_anp_status_updates: The total number of actual status updates performed for Antrea NetworkPolicy Custom Resources",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "irate(antrea_controller_acnp_status_updates[1m])",
     "legendFormat": "ACNP Status Update"
    },
    {
     "expr": "irate(antrea_controller_anp_status_updates[1m])",
     "legendFormat": "ANP Status Update"
    }
   ]
  },
  {
   "title": "Antrea Controller Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\" } | json | line_format `{{.timestamp}} at node {{.nodename}} with level {{.log_level}} from subsystem {{.category}} with message: {{.message}}`"
    }
   ]
  }
 ]
}