#    MASTER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - image: locustio/locust
        name: master
        args: ["--master"]
        volumeMounts:
          - mountPath: /home/locust
            name: locust-config-volume
        ports:
        - containerPort: 5557
          name: master-5557
        - containerPort: 5558
          name: master-5558
        - containerPort: 8089
          name: locust-web-8089
      volumes:
      - name: locust-config-volume
        configMap:
          name: locust-configmap
          items:
          - key: locustfile.py
            path: locustfile.py
---
# WORKER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-worker
  name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - image: locustio/locust
        name: worker
        args: ["--worker", "--master-host=locust-master"]
        volumeMounts:
          - mountPath: /home/locust
            name: locust-config-volume
      volumes:
      - name: locust-config-volume
        configMap:
          name: locust-configmap
          items:
          - key: locustfile.py
            path: locustfile.py
---
# SERVICE 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  type: ClusterIP
  ports:
  - port: 5557
    name: master-5557
  - port: 5558
    name: locust-master-5558
  - port: 8089
    targetPort: 8089
    name: locust-web-8089
  selector:
    app: locust-master
---
# LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: locust-ui
spec:
  type: LoadBalancer
  selector:
    app: locust-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
