{
 "title": "1.- Agent Process Metrics",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "log_category",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Antrea Managed Pods by Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_agent_local_pod_count{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_local_pod_count{instance=~\"^$instance.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Antrea Process",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"^$instance.*\"}[1m])  * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server CPU Usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\".*6443$\"} [1m]) * 100",
     "legendFormat": "min {{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Resident and Memory Status ",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\".*6443$\"}",
     "legendFormat": "resident memory @ {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\".*6443$\"}",
     "legendFormat": "virtual memory @ {{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Status",
   "type": "timeseries",
   "description": "Virtual memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory Status",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Antrea Logs per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (log_level) (rate({job=\"fluentbit-antrea\", nodename=~\"$instance\", agent_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m]))",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "description": "Open File Descriptors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"^$instance.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(process_max_fds{instance=~\"^$instance.*\"})\n",
     "legendFormat": "Max FDs"
    }
   ]
  }
 ]
}