{
 "title": "2.- Agent OVS Metrics and logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   { "name": "ovs_table", "query": { "query": "antrea_agent_ovs_flow_count" } },
   {
    "name": "operation",
    "query": {
     "query": "antrea_agent_ovs_flow_ops_count"
    }
   },
   {
    "name": "ovs_log_level",
    "query": {}
   },
   {
    "name": "ovs_category",
    "query": {}
   },
   {
    "name": "ip_family",
    "query": {
     "query": "antrea_proxy_total_endpoints_installed"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OVS Table Names",
   "type": "text",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "0=PipelineRootClassifier\n1=ARPSpoofGuard\n2=ARPResponder\n3=Classifier\n4=SpoofGuard\n5=UnSNAT\n7=ConntrackZone\n8=PreRoutingClassifier\n9=SessionAffinity\n10=ServiceLB\n11=EndpointDNAT\n12=AntreaPolicyEgressRule\n13=EgressRule\n14=EgressDefaultRule\n15=EgressMetric\n16=L3Forwarding\n17=EgressMark\n18=L3DecTTL\n19=SNATMark\n20=SNAT\n21=L2ForwardingCalc\n22=TrafficControl\n23=IngressSecurityClassifier\n24=AntreaPolicyIngressRule\n25=IngressRule\n26=IngressDefaultRule\n27=IngressMetric\n28=ConntrackCommit\n29=Output"
   }
  },
  {
   "title": "Agent OVS Flow Count",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}",
     "legendFormat": "table {{table_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "Sum of OVS Entries by Node",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum (antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}) by (instance)",
     "legendFormat": "entries @ {{instance}}"
    }
   ]
  },
  {
   "title": "Sum of OVS Entries by TableID",
   "type": "timeseries",
   "description": "Flow count for each OVS flow table. The TableID is used as a label.\nPolicyEgressRule = 45\nEgressRule = 50\nL3Forwarrding = 70\nSNATTable=71",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum (antrea_agent_ovs_flow_count{instance=~\"^$instance.*\", table_id=~'${ovs_table:regex}'}) by (table_id)",
     "legendFormat": "table {{table_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "OVS Flow Operations by instance",
   "type": "timeseries",
   "description": "Number of OVS flow operations, partitioned by operation type (add, modify and delete).",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(antrea_agent_ovs_flow_ops_count{instance=~\"^$instance.*\", operation=~\"$operation\"}[1m])) by (instance) * 60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  {
   "title": "OVS Flow Operations by operation type",
   "type": "timeseries",
   "description": "Number of OVS flow operations, partitioned by operation type (add, modify and delete).",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(antrea_agent_ovs_flow_ops_count{instance=~\"^$instance.*\", operation=~\"$operation\"}[1m])) by (operation) * 60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  {
   "title": "Flow Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(antrea_agent_ovs_flow_ops_error_count{instance=~\"$instance.*\"}[1m]) * 60",
     "legendFormat": "{{instance}}  {{operation}}"
    }
   ]
  },
  { "title": "OVS Logs Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "OpenvSwitch Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-ovs\",ovs_category=~\"$ovs_category\",ovs_log_level=~\"$ovs_log_level\", nodename=~\"$instance\"} |  json | line_format \"{{.date}} at node {{.nodename}} with level {{.ovs_log_level}} from subsystem {{.ovs_category}} with message: {{.message}}\""
    }
   ]
  },
  {
   "title": "OVS  Events per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"fluentbit-antrea-ovs\", nodename=~\"$instance\", ovs_category=~\"$ovs_category\", ovs_log_level=~\"$ovs_log_level\"} [1m])) by (ovs_log_level)",
     "legendFormat": "{{ovs_log_level}} {{ovs_category}} "
    }
   ]
  }
 ]
}