{
 "title": "3.-  Agent Conntrack and Proxy Metrics",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "ip_family",
    "query": {
     "query": "antrea_proxy_total_endpoints_installed"
    }
   }
  ]
 },
 "panels": [
  { "title": "Conntrack Section", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Antrea ZoneID Conntrack Connection Count",
   "type": "timeseries",
   "description": "antrea_agent_conntrack_total_connection_count: Number of connections in the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_antrea_connection_count: Number of connections in the Antrea ZoneID of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_max_connection_count: Size of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "antrea_agent_conntrack_antrea_connection_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CT Total Connection vs Maximum Percentage",
   "type": "timeseries",
   "description": "antrea_agent_conntrack_total_connection_count: Number of connections in the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_antrea_connection_count: Number of connections in the Antrea ZoneID of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.\n\nantrea_agent_conntrack_max_connection_count: Size of the conntrack table. This metric gets updated at an interval specified by flowPollInterval, a configuration parameter for the Agent.",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(antrea_agent_conntrack_total_connection_count{instance=~\"^$instance.*\"}/antrea_agent_conntrack_max_connection_count{instance=~\"^$instance.*\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy and Endpoints Section", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Proxy Endpoints vs Service Updates rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(antrea_proxy_total_endpoints_updates{job=\"antrea-agents\", instance=~\"^$instance.*\"} [$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(antrea_proxy_total_services_updates{job=\"antrea-agents\", instance=~\"^$instance.*\"} [$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Endpoints Installed by Node",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_proxy_total_endpoints_installed {job=\"antrea-agents\", instance=~\"^$instance.*\", ip_family=~\"$ip_family\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}