{
 "title": "4.- Agent Network Policy Metrics and Logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-agents\"}"
    }
   },
   {
    "name": "action",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Network Policies by Node ",
   "type": "stat",
   "description": "Number of NetworkPolicies on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "antrea_agent_networkpolicy_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Egress Network Policies",
   "type": "stat",
   "description": "Number of egress NetworkPolicy rules on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_egress_networkpolicy_rule_count{instance=~\"^$instance.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Denied Connection Count by Node",
   "type": "timeseries",
   "description": "Number of denied connections detected by Flow Exporter deny connections tracking. This metric gets updated when a flow is rejected/dropped by network policy.",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "antrea_agent_denied_connection_count{instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Ingress Network Policies",
   "type": "stat",
   "description": "Number of ingress NetworkPolicy rules on local Node which are managed by the Antrea Agent.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(antrea_agent_ingress_networkpolicy_rule_count{instance=~\"^$instance.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Hitting Network Policy by Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (action) (sum_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"$action\"} | json | unwrap packetLength | __error__=\"\" [$__interval]))\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Network Policy Hits by Action",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (action) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"$action\"} [$__interval]))\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Network Policies Log Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Antrea Network Policy Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-netpolicy\",action=~\"$action\", nodename=~\"$instance\"} \n|  json \n|  line_format \"{{.action}} {{.protocol}} packet from Source:{{.sourceIP}}:{{.sourcePort}} to Destination:{{.destinationIP}}:{{.destinationPort}} hitting rule {{.ruleName}} with reference {{.antreaNativePolicyReference}} at node {{.nodename}}\""
    }
   ]
  },
  { "title": "Allowed Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Allowed Rules Hits",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ruleName) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{ruleName}}"
    }
   ]
  },
  {
   "title": "Allowed DestinationIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Allowed SourceIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sourceIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Allowed Services",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationPort, protocol, action) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` [$__interval])) ",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Allowed Conversations",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol, sourceIP, destinationIP, destinationPort) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=\"Allow\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{sourceIP}} - {{destinationIP}} {{protocol}} {{destinationPort}}"
    }
   ]
  },
  { "title": "Denied Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Denied Rules Hits",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(ruleName) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Reject|Drop\"} | json | __error__=`` [$__interval])))",
     "legendFormat": "{{ruleName}}"
    }
   ]
  },
  {
   "title": "Denied SourceIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (sourceIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` [$__interval])))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Denied DestinationIP",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationIP) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Denied Services",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destinationPort, protocol, action) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Reject|Drop\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "{{destinationIP}}"
    }
   ]
  },
  {
   "title": "Denied Conversations",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (protocol, sourceIP, destinationIP, destinationPort) (count_over_time({job=\"fluentbit-antrea-netpolicy\", action=~\"Drop|Reject\"} | json | __error__=`` [$__interval])) ",
     "legendFormat": "{{sourceIP}} - {{destinationIP}} {{protocol}} {{destinationPort}}"
    }
   ]
  }
 ]
}