{
 "title": "6.- Controller Metrics and Logs",
 "tags": [ "antrea_v1.10" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=\"antrea-controllers\"}"
    }
   },
   {
    "name": "log_category",
    "query": {}
   },
   {
    "name": "log_level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Logs by log level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (log_level) (count_over_time({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__interval]))",
     "legendFormat": "{{log_level}}"
    }
   ]
  },
  {
   "title": "Agent Logs count by Category",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller_log_category) (count_over_time({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [$__interval]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Antrea Controller Logs per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate({job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\"} [1m])) by (log_level)",
     "legendFormat": "{{log_level}} {{category}} "
    }
   ]
  },
  {
   "title": "Queue Lenght",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "antrea_controller_length_address_group_queue",
     "legendFormat": "Address Group Queue"
    },
    {
     "expr": "antrea_controller_length_network_policy_queue",
     "legendFormat": "Network Policy Queue"
    },
    {
     "expr": "antrea_controller_length_applied_to_group_queue",
     "legendFormat": "Applied To Queue"
    }
   ]
  },
  {
   "title": "Nodes Running Antrea Controller",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "up{job=\"antrea-controllers\", instance=~\"^$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Process CPU Seconds",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"antrea-controllers\"}[60s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(antrea_controller_network_policy_sync_duration_milliseconds_sum[5m])",
     "legendFormat": "Network Policy Sync Duration (msec)"
    },
    {
     "expr": "irate(antrea_controller_address_group_sync_duration_milliseconds_sum[5m])",
     "legendFormat": "Address Group Sync Duration (msec)"
    },
    {
     "expr": "rate(antrea_controller_applied_to_group_sync_duration_milliseconds_sum[5m])",
     "legendFormat": "Applied-to-Group Sync Duration (msec)"
    }
   ]
  },
  {
   "title": "Controller Processed Rate",
   "type": "timeseries",
   "description": "antrea_controller_address_group_processed: The total number of address-group processed\n\nantrea_controller_applied_to_group_processed: The total number of applied-to-group processed\n\nantrea_controller_network_policy_processed: The total number of internal-networkpolicy processed",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "irate(antrea_controller_network_policy_processed[5m])",
     "legendFormat": "Network Policy Processed"
    },
    {
     "expr": "irate(antrea_controller_applied_to_group_processed[5m])",
     "legendFormat": "Applied-to-Group Processed"
    },
    {
     "expr": "irate(antrea_controller_address_group_processed[5m])",
     "legendFormat": "Address Groups Processed"
    }
   ]
  },
  {
   "title": "ANP and ACNP Status Update Rate",
   "type": "timeseries",
   "description": "antrea_controller_acnp_status_updates: The total number of actual status updates performed for Antrea ClusterNetworkPolicy Custom Resources\n\nantrea_controller_anp_status_updates: The total number of actual status updates performed for Antrea NetworkPolicy Custom Resources",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "irate(antrea_controller_acnp_status_updates[5m])",
     "legendFormat": "ACNP Status Update"
    },
    {
     "expr": "irate(antrea_controller_anp_status_updates[5m])",
     "legendFormat": "ANP Status Update"
    }
   ]
  },
  {
   "title": "Antrea Controller Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{job=\"fluentbit-antrea-controller\", nodename=~\"$instance\", controller_log_category=~\"$log_category\", log_level=~\"$log_level\" } | json | line_format `{{.timestamp}} at node {{.nodename}} with level {{.log_level}} from subsystem {{.category}} with message: {{.message}}`"
    }
   ]
  }
 ]
}